[phases.setup]
  commands = [
    "composer install --no-dev --optimize-autoloader",
    "npm install"
  ]

[phases.build]
  commands = [
    "npm run build"
  ]

[phases.start]
  commands = [
    "php artisan migrate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php-fpm"
  ]
